### ISSUE TITLE
Random Spam messages

### ISSUE THREAD

**Issue by Nevsix** [NintendoLink07/MythicIOGrabber#11]
**Describe the bug**
It spams  random in Chat what my Guild Mates not exists.

![Screenshot_81](https://github.com/user-attachments/assets/c45a3cff-4a7b-4681-b4a4-b9a330085f7a)

**Comment by NintendoLink07** [comment]
Hmm, this debug message should not appear normally, sorry for that.
I'll investigate and upload v2.6.1 soon.

**Comment by NintendoLink07** [comment]
Deleted the debug print out, uploading new version now.
