### ISSUE TITLE
Timewalk

### ISSUE THREAD

**Issue by Nevsix** [NintendoLink07/MythicIOGrabber#12]
**Is your feature request related to a problem? Please describe.**
Yeah! Timewalk ist in the HC Tab and can't be choosed if you not HC Dungeon ready.

**Describe the solution you'd like**
Extra Tab for Events or Timewalk.

**Comment by NintendoLink07** [comment]
Hey, thanks for the report.
Currently at work so I'll fix it when I'm home.
New version getting uploaded around 16:00 CEST.

**Comment by NintendoLink07** [comment]
Just uploaded the newest version.
The event dungeons are now at the top of the list under a separate header.

Thanks for pointing out all these bugs, I really appreciate it.
