### ISSUE TITLE
RaidPlanner.lua

### ISSUE THREAD

**Issue by Hexus-Proud** [NintendoLink07/MythicIOGrabber#15]
1x MythicIOGrabber/RaidPlanner.lua:97: attempt to index upvalue 'playerPool' (a nil value)
[string "@MythicIOGrabber/RaidPlanner.lua"]:97: in function <MythicIOGrabber/RaidPlanner.lua:76>
[string "@MythicIOGrabber/RaidPlanner.lua"]:137: in function <MythicIOGrabber/RaidPlanner.lua:135>
[string "@MythicIOGrabber/RaidPlanner.lua"]:147: in function <MythicIOGrabber/RaidPlanner.lua:141>
[string "@MythicIOGrabber/RaidPlanner.lua"]:303: in function <MythicIOGrabber/RaidPlanner.lua:302>
[string "@MythicIOGrabber/RaidPlanner.lua"]:571: in function `loadRaidPlanner'
[string "@MythicIOGrabber/UI.lua"]:199: in function `createFrames'
[string "@MythicIOGrabber/MythicIOGrabber.lua"]:22: in function <MythicIOGrabber/MythicIOGrabber.lua:10>

Locals:
text = ""
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'playerPool' (a nil value)"
miog = <table> {
 openRaidLib = <table> {
 }
 DUNGEON_ENCOUNTER_INFO = <table> {
 }
 DEBUG_APPLICANT_MEMBER_INFO = <table> {
 }
 DIFFICULTY_ID_INFO = <table> {
 }
 DEBUG_TIER_TABLE = <table> {
 }
 INELIGIBILITY_REASONS = <table> {
 }
 debug = <table> {
 }
 RACES = <table> {
 }
 CUSTOM_DIFFICULTY_ORDER = <table> {
 }
 BATTLEMASTER_INFO = <table> {
 }
 BASE_ITEM_TRACK_INFO = <table> {
 }
 DIFFICULTY = <table> {
 }
 RAID_DIFFICULTIES = <table> {
 }
 FILTER_DESCRIPTIONS = <table> {
 }
 DEBUG_ROLE_TABLE = <table> {
 }
 ACTIVITY_BACKGROUNDS = <table> {
 }
 LFG_ID_INFO = <table> {
 }
 MAP_INFO = <table> {
 }
 RaidSheet = Frame {
 }
 fullPlayerName = "Paterius-Proudmoore"
 EntryCreation = MythicIOGrabber_EntryCreation {
 }
 pveFrame2 = MythicIOGrabber_PVEFrameReplacement {
 }
 Teleports = Frame {
 }
 ClassPanel = MythicIOGrabber_ClassPanel {
 }
 CLASSES = <table> {
 }
 MAP_CHALLENGE_MODE_INFO = <table> {
 }
 NewFilterPanel = MythicIOGrabber_NewFilterPanel {
 }
 shortPlayerName = "Paterius"
 SearchPanel = MythicIOGrabber_SearchPanel {
 }
 ApplicationViewer = MythicIOGrabber_ApplicationViewer {
 }
 StatisticsPage = Frame {
 }
 fzy = <table> {
 }
 GEARING_CHART = <table> {
 }
 PLAYSTYLE_STRINGS = <table> {
 }
 PVPStatistics = Frame {
 }
 C = <table> {
 }
 RaidStatistics = Frame {
 }
 MPlusStatistics = Frame {
 }
 F = <table> {
 }
 Statistics = Frame {
 }
 Gearing = Frame {
 }
 MainTab = Frame {
 }
 favouredPlayersPanel = Frame {
 }
 PartyCheck = Frame {
 }
 RAW = <table> {
 }
 statisticsDB = <table> {
 }
 TELEPORT_FLYOUT_IDS = <table> {
 }
 defaultFilters = <table> {
 }
 SPECIALIZATIONS = <table> {
 }
 CLRSCC = <table> {
 }
 referencePVPButtons = <table> {
 }
 GROUP_ID_TO_LFG_ID = <table> {
 }
 BLANK_BACKGROUND_INFO = <table> {
 }
 SEARCH_LANGUAGES = <table> {
 }
 checkSystem = <table> {
 }
 FONTS = <table> {
 }
 DIFFICULTY_ID_TO_SHORT_NAME = <table> {
 }
 SLOT_FILTER_TO_NAME = <table> {
 }
 GROUP_ACTIVITY = <table> {
 }
 MainFrame = MythicIOGrabber_PVEFrameReplacement {
 }
 SEASONAL_MAP_IDS = <table> {
 }
 SEASONAL_CHALLENGE_MODES = <table> {
 }
 CURRENCY_INFO = <table> {
 }
 ITEM_LEVEL_JUMPS = <table> {
 }
 VAULT_PROGRESS = <table> {
 }
 WEIGHTS_TABLE = <table> {
 }
 APPLICANT_STATUS_INFO = <table> {
 }
 DUNGEON_DIFFICULTIES = <table> {
 }
 DROPCHECKER_MAP_IDS = <table> {
 }
 MAX_GROUP_SIZES = <table> {
 }
 LOCALIZED_SPECIALIZATION_NAME_TO_ID = <table> {
 }
 AJ_CLRSCC = <table> {
 }
 INSTANCE_SHORT_NAME = <table> {
 }
 Plugin = MythicIOGrabber_PluginFrame {
 }
 SLOT_ID_INFO = <table> {
 }
 MPLUS_SEASONS = <table> {
 }
 EXPANSION_INFO = <table> {
 }
 ONCE = true
 LFG_DUNGEONS_INFO = <table> {
 }
 COLOR_BREAKPOINTS = <table> {
 }
 DEBUG_DEV_CHARACTERS = <table> {
 }
 ITEM_QUALITY_COLORS = <table> {
 }
 DIFFICULTY_NAMES_TO_ID = <table> {
 }
 INSTANCE_IDS = <table> {
 }
 JOURNAL_CREATURE_INFO = <table> {
 }
 ICON_COORDINATES = <table> {
 }
 BRACKETS = <table> {
 }
 ACTIVITY_INFO = <table> {
 }
 DEBUG_RAIDER_IO_PROFILES = <table> {
 }
 REALM_LOCAL_NAMES = <table> {
 }
 DEBUG_APPLICANT_DATA = <table> {
 }
 DEBUG_SPEC_TABLE = <table> {
 }
 CUSTOM_CATEGORY_ORDER = <table> {
 }
 DIFFICULTY_ID_TO_COLOR = <table> {
 }
 CLASS_SPEC_FOR_AFFIXES = <table> {
 }
 roleRemainingKeyLookup = <table> {
 }
 CLASSFILE_TO_ID = <table> {
 }
 JOURNAL_INSTANCE_INFO = <table> {
 }
}
playerPool = nil

**Comment by NintendoLink07** [comment]
Thank you for the report, currently not at home so I'll fix this in around 12 hours from now, sorry for the inconvenience inconvenience.

**Comment by NintendoLink07** [comment]
This issue is fixed in version [3.0.0](https://github.com/NintendoLink07/MythicIOGrabber/releases/tag/3.0.0), which has now been released on CurseForge/Wago Addons.
Again, thank you for the report.
